import { GlobeAltIcon } from "@heroicons/react/24/outline";
import { PiCertificateBold } from "react-icons/pi";
import { MdGroups ,MdLightbulbOutline } from "react-icons/md";
import { CiCalendarDate, CiLocationOn } from "react-icons/ci";
import { TbClockHour4 } from "react-icons/tb";
import { BsGrid3X3 } from "react-icons/bs";
import { FaBars ,FaChartLine } from "react-icons/fa6";
import { IoPeople , IoShieldCheckmarkSharp  ,IoCheckmarkCircleOutline ,IoLogoFacebook} from "react-icons/io5";
import { BiSmile } from "react-icons/bi";
import { IoMdTrendingUp } from "react-icons/io";
import { SiNextra } from "react-icons/si";

import {
  FaInstagramSquare,
  FaWhatsappSquare,
  FaLinkedin,
  FaWhatsapp,
  FaInstagram,
  FaFacebookF,
  FaLinkedinIn,
  FaLongArrowAltRight,
  FaLongArrowAltLeft,
  FaUser,
  FaStar,
  FaBookOpen
} from "react-icons/fa";

import {
  AlignLeft,
  X,
  Moon,
  SunMedium,
  Facebook,
  Angry,
  Clock,
  BookOpen,
  Star,
  Users,
  Check,
  Infinity as LucideInfinity,
  Award,
  ShieldCheck,
  ArrowRight,
  ChevronRight,
  Laptop,
  Twitter,
  Globe,
  Calendar,
  Search,
  User,
  ShoppingCart,
  Heart,
  CreditCard,
} from "lucide-react";

export {
  LucideInfinity,
  GlobeAltIcon,
  AlignLeft,
  X,
  SunMedium,
  Moon,
  Facebook,
  Angry,
  IoLogoFacebook,
  FaInstagramSquare,
  FaWhatsappSquare,
  FaLinkedin,
  FaLongArrowAltRight,
  FaLongArrowAltLeft,
  CiCalendarDate,
  TbClockHour4,
  CiLocationOn,
  Check,
  Star,
  IoPeople,
  Clock,
  BookOpen,
  Users,
  BsGrid3X3,
  FaBars,
  MdLightbulbOutline,
  FaWhatsapp,
  FaInstagram,
  FaFacebookF,
  FaLinkedinIn,
  Award,
  ShieldCheck,
  ArrowRight,
  ChevronRight,
  MdGroups,
  FaUser,
  PiCertificateBold,
  Laptop,
  Twitter,
  Globe,
  Calendar,
  Search,
  IoShieldCheckmarkSharp,
  BiSmile,
  IoMdTrendingUp,
  SiNextra,
  FaBookOpen,
  IoCheckmarkCircleOutline,
  FaChartLine,
  FaStar,
  User,
  ShoppingCart,
  Heart,
  CreditCard,
};
